config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'first_preferences' => 'first_preferences#show'

end

app/models/first_preferences.rb
require 'csv'

class FirstPreferences < ActiveRecord::Base

  def self.formals(polling_place = 'Newlands (Wills)')
    FirstPreferences
        .where(polling_place: polling_place)
        .where('ballot_position <> 999')
        .order('ordinary_votes desc')
  end

  def self.informals(polling_place = 'Newlands (Wills)')
    FirstPreferences
        .where(polling_place: polling_place)
        .where('ballot_position = 999')
        .order('ordinary_votes desc')
  end

  def styles
    styles = []
    styles << 'bg-success' if party_ab == 'GRN'
    styles << 'bg-danger' if ballot_position == 999
    styles.join(' ')
  end

  def self.import(file_name, options = {})

    count = 0
    CSV.foreach(file_name, skip_lines: /^2013 .*/, headers: true) do |row|
      values = {
          state_ab: row['StateAb'],
          division_id: row["DivisionID"],
          division_name: row['DivisionNm'],
          polling_place_id: row['PollingPlaceID'],
          polling_place: row['PollingPlace'],
          candidate_id: row['CandidateID'],
          candidate_surname: row['Surname'],
          candidate_given_name: row['GivenNm'],
          ballot_position: row['BallotPosition'],
          elected: row['Elected'] == 'Y',
          historic_elected: row['HistoricElected'] == 'Y',
          party_ab: row['PartyAb'],
          party_name: row['PartyNm'],
          ordinary_votes: row['OrdinaryVotes'],
          swing: row['Swing'].to_f
      }
      p FirstPreferences.create(values)

      count = count + 1
      break if options[:count] && options[:count] <= count

      true
    end
    puts "Imported #{count} rows."
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/first_preferences_controller.rb
class FirstPreferencesController < ApplicationController

  def show
    @preferences = FirstPreferences.formals
    @informals = FirstPreferences.informals
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/first_preferences/show.html.erb
<h1>First Preferences</h1>
<h2>2013 Election Results</h2>
<% @preferences.each do |pref| %>
    <div class="row <%= pref.styles %>">
      <div class="col-sm-10">
        <%= pref.candidate_surname%>,
        <%= pref.candidate_given_name %>
        <% if pref.elected? %>
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
        <% end %>
      </div>
      <div class="col-sm-1"><%= pref.party_ab %></div>
      <div class="col-sm-2">
        <div class="row">
          <div class="col-sm-6 text-right"><%= pref.ordinary_votes %></div>
          <div class="col-sm-6 text-right"><%= "%0.1f" % pref.swing %></div>
        </div>
      </div>
    </div>
<% end %>
<% @informals.each do |pref| %>
    <div class="row <%= pref.styles %>">
      <div class="col-sm-10">INFORMAL</div>
      <div class="col-sm-2">
        <div class="row">
          <div class="col-sm-6 text-right"><%= pref.ordinary_votes %></div>
          <div class="col-sm-6 text-right"><%= "%0.1f" % pref.swing %></div>
        </div>
      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <title>ElectionPolling</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <%= yield %>

</div><!-- /.container -->

</body>
</html>

app/views/welcome/index.html.erb
<h1>Options</h1>

<%= link_to 'First Preferences', first_preferences_path, class: 'btn btn-primary' %>